---
- name: Start Jenkins container
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    state: started
    volumes:
      - "{{ jenkins_home_directory }}:/var/jenkins_home"
    ports:
      - "{{ jenkins_http_port }}:8080"
      - "{{ jenkins_agent_tcp_port }}:50000"
  become: true

- name: Create plugins.txt file
  template:
    dest: /var/jenkins_home/plugins.txt
    src: var/jenkins_home/plugins.txt.j2
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  notify: Install Jenkins plugins
  become: true
