---
- name: Restart Jenkins container
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    state: restarted
  become: true

- name: Install Jenkins plugins
  jenkins_plugins:
    name: "{{ item.name }}"
    url: "{{ jenkins_url }}"
    version: "{{ item.version }}"
    with_dependencies: no
    state: present
  with_items: "{{ jenkins_plugins }}"
  notify: Restart Jenkins container
  when: "jenkins_plugins is defined"
